name: 'Execução agendada'

on:
  schedule:
    - cron: '0 6 * * 1' # run every monday at 06:00

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando Yarn...
        run: npm install -g yarn

      - name: Instalando dependencies...
        run: yarn

      - name: Instalando playwright...
        run: yarn playwright install

      - name: Executando testes E2E...
        run: yarn run e2e
