# THIS IS A PIPELINE WORKFLOW

# CI de nível 1 - Disparo manual a partir de 1 clique

# nome do nosso pipeline
name: 'Execução agendada'

# Regras de disparo. Triggers
# Gatilho de execução manual --- workflow_dispath
on:
  schedule: 0 6 * * 1
  #a - minuto
  #b - hora
  #c - dia do mês
  #d - mês
  #e - dia da semana
  #rodar o regressivo toda segunda-feira pela manhã
  #'cron'
  #a b c d e
  #0 6 * * 1

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # maquina de o job vai executar / https://github.com/actions/runner-images
    runs-on: ubuntu-latest

    # passos do script de build - steps
    steps:
      # clone do projecto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn...
        run: npm install -g yarn

      #instalação das dependecias
      - name: Instalando dependencies...
        run: yarn

      # Instalação playwright
      - name: Instalando playwright...
        run: yarn playwright install

      # Execução dos testes e2e
      - name: Executando testes E2E...
        run: yarn run e2e
